language: rust
sudo: false
rust:
  - stable
  - beta
  - nightly
os:
  - linux
matrix:
  allow_failures:
    - rust: nightly
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
script:
  - cargo build -v
  - cargo test -v
